version: '3.7'

services:
  app:
    image: eventos
    build: .
    environment:
      NODE_ENV: development
      REDIS_HOST: cache
      REDIS_PORT: 6379
    ports:
      - 3333:3333
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./src/shared/infra/http/server.js"]
